apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort  # You can use NodePort for testing in kind
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8081  # The port the service listens on
      targetPort: 8081  # The port the container listens on
      nodePort: 30001  # NodePort for external access
